name: EpicVoz
favicon: null
layout_spectrum: 0.26585
typography_spectrum: 0.41866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#137fd7'
    - '#a2b8c3'
    - '#434959'
    - '#9a3a3b'
    - '#758791'
  brandStrength: 0.5
  lightness: 0.821438041748479
  saturation: 0.35064736916683614
  rhythmicContrast: 0.39090113365091383
purpose: []
