name: EpicVoz
favicon: null
layout_spectrum: 0.49266
typography_spectrum: 0.41866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d60000'
    - '#104d79'
    - '#b3595b'
    - '#7aacd6'
  brandStrength: 0.25
  lightness: 0.821438041748479
  saturation: 0.35064736916683614
  rhythmicContrast: 0.39090113365091383
purpose: []
