name: EpicVoz
favicon: null
layout_spectrum: 0.49106
typography_spectrum: 0.41866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d41608'
    - '#000000'
    - '#0302cc'
    - '#b2b2b2'
    - '#393a3f'
  brandStrength: 0.5625
  lightness: 0.821438041748479
  saturation: 0.35064736916683614
  rhythmicContrast: 0.39090113365091383
purpose: []
